# Generated by Django 5.0.3 on 2026-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_chat_chatme_session_70d41b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('MOOD_RECOMMENDATION', 'Mood Recommendation'), ('NUTRITION_PLAN_REQUEST', 'Nutrition Plan Request'), ('CLARIFICATION', 'Clarification'), ('GREETING', 'Greeting')], default='CLARIFICATION', max_length=50),
        ),
    ]
