# Generated by Django 5.0.3 on 2026-05-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatsession_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='conversation_state',
            field=models.CharField(default='READY', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pending_food_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pending_intent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pending_mood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('MOOD_RECOMMENDATION', 'Mood Recommendation'), ('NUTRITION_PLAN_REQUEST', 'Nutrition Plan Request'), ('CLARIFICATION', 'Clarification'), ('GREETING', 'Greeting'), ('HELP', 'Help'), ('HEALTHY_ALTERNATIVE', 'Healthy Alternative'), ('HYDRATION', 'Hydration')], default='CLARIFICATION', max_length=50),
        ),
    ]
