# Generated by Django 5.0.3 on 2026-06-04 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_conversation_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecommendation',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatrecommendation',
            name='nutrition_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
