# Generated by Django 5.0.3 on 2026-04-26 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbs_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fat_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('data_source', models.CharField(default='Manual Demo Data — placeholder', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodMoodMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthyAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_food_name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodAllergenTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='nutrition.allergy')),
            ],
        ),
        migrations.CreateModel(
            name='FoodHealthConditionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('WARNING', 'Warning'), ('BLOCKED', 'Blocked')], max_length=50)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_rules', to='nutrition.healthcondition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.CheckConstraint(check=models.Q(('calories__gte', 0)), name='check_calories_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.CheckConstraint(check=models.Q(('protein_g__gte', 0)), name='check_protein_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.CheckConstraint(check=models.Q(('carbs_g__gte', 0)), name='check_carbs_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.CheckConstraint(check=models.Q(('fat_g__gte', 0)), name='check_fat_non_negative'),
        ),
        migrations.AddField(
            model_name='foodhealthconditionrule',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_rules', to='nutrition.fooditem'),
        ),
        migrations.AddField(
            model_name='foodallergentag',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='nutrition.fooditem'),
        ),
        migrations.AddField(
            model_name='foodmoodmapping',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_mappings', to='nutrition.fooditem'),
        ),
        migrations.AddField(
            model_name='healthyalternative',
            name='alternative_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.fooditem'),
        ),
        migrations.AddField(
            model_name='foodmoodmapping',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_mappings', to='nutrition.moodtag'),
        ),
        migrations.AddConstraint(
            model_name='foodallergentag',
            constraint=models.UniqueConstraint(fields=('food', 'allergy'), name='unique_food_allergen'),
        ),
        migrations.AddIndex(
            model_name='healthyalternative',
            index=models.Index(fields=['original_food_name'], name='nutrition_h_origina_280a48_idx'),
        ),
        migrations.AddIndex(
            model_name='foodmoodmapping',
            index=models.Index(fields=['mood', 'priority'], name='nutrition_f_mood_id_0ba6e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodmoodmapping',
            constraint=models.UniqueConstraint(fields=('food', 'mood'), name='unique_food_mood'),
        ),
        migrations.AddConstraint(
            model_name='foodmoodmapping',
            constraint=models.CheckConstraint(check=models.Q(('priority__gte', 0)), name='check_priority_non_negative'),
        ),
    ]
