# Generated by Django 5.0.3 on 2026-05-01 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_waterintakelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foodallergentag',
            index=models.Index(fields=['allergy', 'food'], name='nutrition_f_allergy_dd06b2_idx'),
        ),
        migrations.AddIndex(
            model_name='foodhealthconditionrule',
            index=models.Index(fields=['health_condition', 'risk_level'], name='nutrition_f_health__2de745_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['is_active', 'category'], name='nutrition_f_is_acti_af219c_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionplan',
            index=models.Index(fields=['user', 'created_at'], name='nutrition_n_user_id_d4379b_idx'),
        ),
        migrations.AddIndex(
            model_name='waterintakelog',
            index=models.Index(fields=['user', 'logged_at'], name='nutrition_w_user_id_10a512_idx'),
        ),
    ]
