# Generated by Django 5.0.3 on 2026-06-03 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_foodallergentag_nutrition_f_allergy_dd06b2_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydrationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_key', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('context_type', models.CharField(max_length=50)),
                ('context_key', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('min_cups', models.IntegerField(default=0)),
                ('max_cups', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='allergy',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fiber_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sodium_mg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='sugar_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='healthcondition',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FoodAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, unique=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='nutrition.fooditem')),
            ],
        ),
    ]
