# Generated by Django 5.0.3 on 2026-06-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_hydrationguide_allergy_key_fooditem_fiber_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
