# Generated by Django 5.0.3 on 2026-06-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_alter_fooditem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=255, unique=True)),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('allowed_use', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_plan_role', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_ratio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('composition_note', models.TextField(blank=True)),
                ('component_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_components', to='nutrition.fooditem')),
                ('parent_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_components', to='nutrition.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutritionBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrition_basis', models.CharField(max_length=50)),
                ('basis_amount_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('basis_note', models.TextField(blank=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_basis', to='nutrition.fooditem', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion_key', models.CharField(max_length=255, unique=True)),
                ('portion_name', models.CharField(max_length=255)),
                ('grams', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_reference_portion', models.BooleanField(default=False)),
                ('portion_note', models.TextField(blank=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='nutrition.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='FoodSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=100)),
                ('source_reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('source_note', models.TextField(blank=True)),
                ('source_review_status', models.CharField(blank=True, max_length=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='nutrition.fooditem', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodUsagePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_lookup_allowed', models.BooleanField(default=False)),
                ('tracking_allowed', models.BooleanField(default=True)),
                ('recommendation_allowed', models.BooleanField(default=False)),
                ('plan_allowed', models.BooleanField(default=False)),
                ('safety_review_status', models.CharField(blank=True, max_length=100)),
                ('plan_role', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_policy', to='nutrition.fooditem', unique=True)),
            ],
        ),
    ]
