# Generated by Django 5.0.3 on 2026-04-26 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ULTRA', 'Ultra')], default='FREE', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=50)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='subscriptio_user_id_586440_idx'), models.Index(fields=['tier'], name='subscriptio_tier_26a741_idx'), models.Index(fields=['status'], name='subscriptio_status_5e8870_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageLimitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('CHAT_GUIDANCE', 'Chat Guidance'), ('NUTRITION_PLAN', 'Nutrition Plan'), ('HEALTHY_ALTERNATIVE', 'Healthy Alternative'), ('FOOD_IMAGE_UPLOAD', 'Food Image Upload'), ('INBODY_UPLOAD', 'InBody Upload'), ('DAILY_TRACKING', 'Daily Tracking'), ('WEEKLY_REPORT', 'Weekly Report')], max_length=50)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='subscriptio_user_id_48a236_idx'), models.Index(fields=['feature_key'], name='subscriptio_feature_16fbab_idx'), models.Index(fields=['period_start'], name='subscriptio_period__844496_idx'), models.Index(fields=['period_end'], name='subscriptio_period__9dfce1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usagelimitcounter',
            constraint=models.UniqueConstraint(fields=('user', 'feature_key', 'period_start', 'period_end'), name='unique_usage_limit_period'),
        ),
        migrations.AddConstraint(
            model_name='usagelimitcounter',
            constraint=models.CheckConstraint(check=models.Q(('count__gte', 0)), name='check_count_non_negative'),
        ),
    ]
